### ISSUE TITLE
Cloud foundry environment

### ISSUE THREAD

**Issue by GraydenH** [SAP/cloud-espm-v2#11]
Hi, it seems like this app is intended for the neo environment? Do any changes need to be made to work with the cloud foundry environment?

**Comment by skrishnakumar** [comment]
We have the same application migrated to run on Cloud Foundry. This is available publicly.
https://github.com/SAP/cloud-cf-espm

**Comment by kanika-malhotra-ggn** [comment]
Hi @skrishnakumar 

Could you please share the steps you took to migrate the neo app to cloud-cf-espm?

Thanks
Kanika

**Comment by CHERIANS** [comment]
@kanika-malhotra-ggn have a look at this [blog ](https://blogs.sap.com/2018/12/07/experience-in-migrating-espm-and-shine-applications-from-sap-cloud-platform-neo-to-cloud-foundry-environment/) for the steps.
Best Regards
Stephen
