### ISSUE TITLE
application size exceeds SAP Trial SCP limit

### ISSUE THREAD

**Issue by amitabak** [SAP/cloud-espm-v2#8]
I tried to deploy the WAR on SCP trial account
Getting "Unable to deploy application. The file size exceeds the maximum upload limit of 20 MB."
The war file is 28M

**Comment by skrishnakumar** [comment]
Hi @amitabak 

I was able to deploy the same in my trial account. the ESPM war is 28MB and was able to deploy it. can you please check again from your side?

**Comment by skrishnakumar** [comment]
Since no response, closing this issue. Please open if issue persists
