### ISSUE TITLE
SAP HANA XS

### ISSUE THREAD

**Issue by zygimantus** [SAP/cloud-espm-v2#9]
Is this application fully supported by SAP HANA XS Advanced Model?

**Comment by skrishnakumar** [comment]
Hi @zygimantus , 

this application is to showcase java runtime in SAP cloud platform using HANA as a database. It does not showcase SAP HANA XS Advanced Model.

Anything specific that you are looking at ? For HANA XS Advanced Model, we have a sample application called SHINE (SAP HANA INteractive Education ) https://github.com/SAP/hana-shine-xsa.

**Comment by zygimantus** [comment]
Hi @skrishnakumar , actually yes. I was wondering if it is possible to have a Java application that follows SAP HANA XS Advanced Model and at the same it is build with Spring Boot.

**Comment by skrishnakumar** [comment]
@zygimantus - running spring boot application in XSA advanced model will definitely work.

**Comment by zygimantus** [comment]
@skrishnakumar - thank you for your response. As I understood XSA advanced model uses modules that separate back-end from front-end parts, but what if my Spring Boot application contains SAPUI5 part inside it? Does this mean that I can have only one module for my Spring app without ui module?

**Comment by skrishnakumar** [comment]
@zygimantus Regarding the UI part, having it as a separate module is recommended and then you access your backend service using destination. Also, in XS Advanced you may use the approuter for the routing and the security part. and we usually bundle the approuter component as part of the UI module. So it depends on the specifics as to what best fits for your use case

**Comment by zygimantus** [comment]
@skrishnakumar thank you for your tips. Would you mind me asking one more question regarding working with SAP WEB IDE? What is the best practice to work for several developers at the same project? Because as I understood the workspace is individual for each developer user.

**Comment by skrishnakumar** [comment]
@zygimantus in general, using a version control system like git will help to collaborate. SAP Web IDE in cloud provides to integrate with git 
https://blogs.sap.com/2017/02/14/using-git-in-sap-web-ide-with-multiple-developers/ 
hope this helps.

**Comment by skrishnakumar** [comment]
closing this ticket for now.
